// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCesoPuxmRzrtc1vImahTNMyF4W_MgB_34',
    appId: '1:937476920259:web:1520de497cba23e2092376',
    messagingSenderId: '937476920259',
    projectId: 'test-f55dc',
    authDomain: 'test-f55dc.firebaseapp.com',
    storageBucket: 'test-f55dc.firebasestorage.app',
    measurementId: 'G-CKZ12HVZ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC21qOaYen04oeJalZIrZiOk04qv7BYJgE',
    appId: '1:937476920259:android:f52246e6d1da1b1c092376',
    messagingSenderId: '937476920259',
    projectId: 'test-f55dc',
    storageBucket: 'test-f55dc.firebasestorage.app',
  );
}
